import type { Metadata } from "next"; import Image from "next/image"; import Link from "next/link"; import { ArrowUpRight } from "lucide-react"; import "./nova-demo.css";
import { siteConfig } from "@/lib/site-config";
import { NovaHeader } from "./nova-header"; import { NovaFooter } from "./nova-footer"; import { PropertyCard } from "./property-card"; import { novaProperties } from "./property-data"; import { NovaScrollHero } from "./nova-scroll-hero";
export const metadata:Metadata={title:"NOVA Estates — Curated Cyprus Property",description:"A fictional luxury real-estate website concept by VISION."};
const collections=[{name:"Coastal villas",image:"/images/nova-demo/category-coastal-villas.png",q:"Villa"},{name:"Marina living",image:"/images/nova-demo/category-marina-living.png",q:"Penthouse"},{name:"Private retreats",image:"/images/nova-demo/category-private-retreats.png",q:"Villa"},{name:"New developments",image:"/images/nova-demo/category-new-developments.png",q:"Development"},{name:"Beach houses",image:"/images/nova-demo/category-beach-houses.png",q:"House"},{name:"Signature homes",image:"/images/nova-demo/category-signature-homes.png",q:"Villa"}];
export default function NovaHome(){return <main className="nova-demo"><NovaHeader/><NovaScrollHero/>
<section id="collections" className="nova-section nova-collections"><div className="nova-heading"><div><p className="nova-eyebrow">Curated by place and pace</p><h2>Find the setting<br/>that feels like yours.</h2></div><p>From quiet coastal villas to precise urban residences, every property is selected for its sense of place.</p></div><div className="nova-collection-grid">{collections.map((c,i)=><Link href={`/work/nova-estates/demo/properties?type=${encodeURIComponent(c.q)}`} className="nova-collection" key={c.name}><Image src={c.image} alt="" fill sizes="(max-width:700px) 100vw, 33vw"/><span>0{i+1}</span><h3>{c.name}</h3><ArrowUpRight/></Link>)}</div></section>
<section id="about" className="nova-intro"><div><p className="nova-eyebrow">NOVA Estates</p><h2>Property guidance,<br/><em>made personal.</em></h2></div><div><p>We bring local perspective, careful selection and calm advice to every search. The aim is simple: fewer distractions, better choices and a home that holds its value in more ways than one.</p><Link className="nova-text-link" href="/work/nova-estates/demo/properties">View the collection <ArrowUpRight/></Link></div></section>
<section className="nova-section nova-featured"><div className="nova-heading"><div><p className="nova-eyebrow">Selected homes</p><h2>Featured properties.</h2></div><Link className="nova-text-link" href="/work/nova-estates/demo/properties">View all properties <ArrowUpRight/></Link></div><div className="nova-property-grid">{novaProperties.map((p,i)=><PropertyCard property={p} priority={i<2} key={p.slug}/>)}</div></section>
<section className="nova-agent" aria-labelledby="nova-agent-title"><div className="nova-agent-photo"><Image src="/images/nova-demo/elena-christou.png" alt="Elena Christou, Senior Property Advisor" fill sizes="(max-width: 700px) 100vw, 42vw"/></div><div className="nova-agent-copy"><p className="nova-eyebrow">Your property advisor</p><h2 id="nova-agent-title">Elena<br/><em>Christou.</em></h2><p className="nova-agent-role">Senior Property Advisor · Cyprus</p><p>Elena brings local market knowledge and a calm, considered approach to every search. From a first shortlist to a private viewing, she keeps each next step clear and personal.</p><a className="nova-text-link" href={`mailto:${siteConfig.email}?subject=Private%20property%20enquiry`}>Speak with Elena <ArrowUpRight/></a></div></section>
<section id="contact" className="nova-contact"><div className="nova-contact-panel"><p className="nova-eyebrow">Private property search</p><h2>Begin with<br/><em>what matters.</em></h2><p>Tell us the setting, pace and details you have in mind. We will return with a considered shortlist shaped around you.</p><a className="nova-button nova-button-light" href={`mailto:${siteConfig.email}`}>Request a private shortlist <ArrowUpRight/></a></div></section><NovaFooter/></main>}
