import type { Metadata } from "next";
import { siteConfig } from "@/lib/site-config";
export const metadata: Metadata = { title: "Privacy Policy", robots: { index: true, follow: true }, alternates: { canonical: "/privacy" } };

const privacyEmail = siteConfig.email;

export default function PrivacyPage() {
  return <main>
    <section className="legal-hero"><div className="site-container"><p className="eyebrow">Legal</p><h1>Privacy Policy</h1><p>This policy explains how FOUND. may collect and use personal information when you use this website or communicate with us.</p></div></section>
    <article className="legal-content site-container">
      <section><h2>1. Introduction</h2><p>FOUND., based in Cyprus, may collect and process personal information when you submit the Contact form, request a Free Website Audit, communicate directly with us, or use this website where optional analytics or cookies have been enabled with your consent.</p></section>
      <section><h2>2. Information we may collect</h2><p>Depending on how you interact with FOUND., we may collect:</p><ul><li>Your name and business or company name.</li><li>Your email address and phone number.</li><li>Your website address, industry and city or location.</li><li>Your business goals, current problems, message or request details and budget information.</li><li>Information included in a Free Website Audit request and any audit scores or internal follow-up notes created while handling that request.</li><li>Source and campaign attribution, such as UTM parameters, where available.</li><li>Technical, cookie and analytics information where those features are configured and optional analytics consent has been given.</li></ul></section>
      <section><h2>3. How information is used</h2><p>We may use information to respond to enquiries, prepare website audit responses, manage potential client relationships, provide requested services, maintain internal business records, understand website performance where analytics consent is given, and prevent spam, misuse or security abuse.</p></section>
      <section><h2>4. Legal basis</h2><p>Where applicable, information may be processed with your consent, to take steps at your request before entering into a contract, for reasonable business interests such as responding to enquiries and operating the website, or to meet legal obligations. The basis used depends on the information and the reason it is processed.</p></section>
      <section><h2>5. Cookies, analytics and spam protection</h2><p>Essential storage may be used for core website functions and to remember your cookie choice. Optional analytics only starts after consent and only where an analytics service has been configured. You can change your analytics choice through Cookie Settings.</p><p>Where configured, technical spam-protection tools may process limited technical information needed to assess and prevent automated or abusive submissions. We do not describe analytics or spam-protection services as active unless they have been enabled for the website.</p></section>
      <section><h2>6. Third-party services</h2><p>FOUND. may use third-party providers for hosting, database services, analytics, email delivery, spam protection or other operational functions. Those providers may process information only where needed to provide their services and remain subject to their own terms and privacy practices.</p></section>
      <section><h2>7. Data retention and security</h2><p>We retain personal information only for as long as reasonably necessary for the purpose for which it was collected, subject to any applicable legal or operational requirements.</p><p>Reasonable technical and organisational measures are used to protect information. No website or online transmission method can guarantee absolute security.</p></section>
      <section><h2>8. Data sharing</h2><p>FOUND. does not sell personal information. Information may be shared with service providers where reasonably necessary to operate the website, respond to a request or provide an agreed service. It may also be disclosed where required by applicable law.</p></section>
      <section><h2>9. Your rights</h2><p>Depending on applicable law and the circumstances, you may have rights to request access to your personal information, ask for inaccurate information to be corrected, request deletion or restriction, object to certain processing, and withdraw consent where processing relies on consent.</p><p>Some rights may be subject to legal or operational limits. We may need enough information to verify and respond to a request.</p></section>
      <section><h2>10. Contact</h2><p>For privacy questions or requests, contact FOUND. at <a href={`mailto:${privacyEmail}`}>{privacyEmail}</a>.</p></section>
    </article>
  </main>;
}
