"use client";

import { useMemo, useState } from "react";
import { Eye, Search, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { leadStatuses } from "@/lib/site-config";
import { notifyAdminDataChanged } from "@/components/admin-dashboard-sync";

type Lead = { id: number; createdAt: Date | string; name: string; businessName: string; email: string; phone: string; website: string; service: string; packageName: string; message: string; status: string; source: string; priority: string; estimatedValue: number | null; notes: string; utmSource: string; utmMedium: string; utmCampaign: string; updatedAt: Date | string; utmContent: string; utmTerm: string };

export function AdminLeadsTable({ initialRows }: { initialRows: Lead[] }) {
  const [rows, setRows] = useState(initialRows); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("ALL"); const [sourceFilter, setSourceFilter] = useState("ALL"); const [campaignFilter, setCampaignFilter] = useState("ALL");
  const sources = useMemo(() => [...new Set(rows.map((row) => row.utmSource || row.source).filter(Boolean))].sort(), [rows]);
  const campaigns = useMemo(() => [...new Set(rows.map((row) => row.utmCampaign).filter(Boolean))].sort(), [rows]);
  const visible = useMemo(() => rows.filter((row) => (filter === "ALL" || row.status === filter) && (sourceFilter === "ALL" || (row.utmSource || row.source) === sourceFilter) && (campaignFilter === "ALL" || row.utmCampaign === campaignFilter) && `${row.name} ${row.businessName} ${row.email} ${row.service}`.toLowerCase().includes(query.toLowerCase())), [rows, query, filter, sourceFilter, campaignFilter]);
  async function remove(id: number) { const response = await fetch(`/api/admin/leads/${id}`, { method: "DELETE" }); if (response.ok) { setRows((current) => current.filter((row) => row.id !== id)); notifyAdminDataChanged(); } }
  return <section><div className="admin-filters"><div className="admin-search"><Search /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, business, email or service" /></div><select className="admin-native-select" aria-label="Filter leads by status" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="ALL">All statuses</option>{leadStatuses.map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select><select className="admin-native-select" aria-label="Filter leads by source" value={sourceFilter} onChange={(event) => setSourceFilter(event.target.value)}><option value="ALL">All sources</option>{sources.map((source) => <option key={source} value={source}>{source}</option>)}</select><select className="admin-native-select" aria-label="Filter leads by campaign" value={campaignFilter} onChange={(event) => setCampaignFilter(event.target.value)}><option value="ALL">All campaigns</option>{campaigns.map((campaign) => <option key={campaign} value={campaign}>{campaign}</option>)}</select></div>
    <div className="admin-table-wrap"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Name</TableHead><TableHead>Business</TableHead><TableHead>Email</TableHead><TableHead>Service</TableHead><TableHead>Package</TableHead><TableHead>Status</TableHead><TableHead>Source</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{visible.map((row) => <TableRow key={row.id}><TableCell>{new Date(row.createdAt).toLocaleDateString("en-GB")}</TableCell><TableCell>{row.name}</TableCell><TableCell>{row.businessName}</TableCell><TableCell><a href={`mailto:${row.email}`}>{row.email}</a></TableCell><TableCell>{row.service || "-"}</TableCell><TableCell>{row.packageName || "-"}</TableCell><TableCell><span className={`status-pill status-${row.status.toLowerCase()}`}>{row.status.replaceAll("_", " ")}</span></TableCell><TableCell>{row.utmSource || row.source}</TableCell><TableCell><div className="table-actions"><LeadSheet row={row} onUpdate={(updated) => setRows((current) => current.map((item) => item.id === updated.id ? updated : item))} /><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="icon-sm" aria-label={`Delete ${row.businessName}`}><Trash2 /></Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this lead?</AlertDialogTitle><AlertDialogDescription>This permanently removes {row.businessName} from the database.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={() => remove(row.id)}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></TableCell></TableRow>)}</TableBody></Table>{visible.length === 0 && <p className="empty-table">No leads match the current filters.</p>}</div>
  </section>;
}

function LeadSheet({ row, onUpdate }: { row: Lead; onUpdate: (lead: Lead) => void }) {
  const [status, setStatus] = useState(row.status); const [priority, setPriority] = useState(row.priority); const [notes, setNotes] = useState(row.notes); const [estimatedValue, setEstimatedValue] = useState(row.estimatedValue?.toString() ?? ""); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  async function save() { setSaving(true); setSaved(false); setError(""); try { const response = await fetch(`/api/admin/leads/${row.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, priority, notes, estimatedValue: estimatedValue ? Number(estimatedValue) : null }) }); const result = await response.json() as { lead?: Lead }; if (!response.ok || !result.lead) throw new Error("Changes could not be saved."); onUpdate(result.lead); notifyAdminDataChanged(); setSaved(true); } catch (cause) { setError(cause instanceof Error ? cause.message : "Changes could not be saved."); } finally { setSaving(false); } }
  return <Sheet><SheetTrigger asChild><Button variant="ghost" size="icon-sm" aria-label={`View ${row.businessName}`}><Eye /></Button></SheetTrigger><SheetContent className="admin-detail-sheet"><SheetHeader><SheetTitle>{row.businessName}</SheetTitle><SheetDescription>{row.name} · {row.email}</SheetDescription></SheetHeader><div className="admin-detail-body" onChangeCapture={() => setSaved(false)}><div className="detail-pairs"><div><span>Phone</span><a href={`tel:${row.phone}`}>{row.phone || "Not supplied"}</a></div><div><span>Website</span><a href={row.website || undefined}>{row.website || "Not supplied"}</a></div><div><span>Service</span><strong>{row.service || "Not specified"}</strong></div><div><span>Package</span><strong>{row.packageName || "Not specified"}</strong></div></div><div className="detail-message"><span>Message</span><p>{row.message}</p></div><div className="form-field"><Label htmlFor={`status-${row.id}`}>Status</Label><select id={`status-${row.id}`} className="site-select" value={status} onChange={(event) => setStatus(event.target.value)}>{leadStatuses.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select></div><div className="form-field"><Label htmlFor={`priority-${row.id}`}>Priority</Label><select id={`priority-${row.id}`} className="site-select" value={priority} onChange={(event) => setPriority(event.target.value)}>{["HOT","WARM","COLD"].map((item) => <option key={item} value={item}>{item}</option>)}</select></div><div className="form-field"><Label htmlFor={`value-${row.id}`}>Estimated value</Label><Input id={`value-${row.id}`} type="number" min="0" step="10" value={estimatedValue} onChange={(event) => setEstimatedValue(event.target.value)} /></div><div className="form-field"><Label htmlFor={`notes-${row.id}`}>Internal notes</Label><Textarea id={`notes-${row.id}`} rows={6} value={notes} onChange={(event) => setNotes(event.target.value)} /></div>{error && <p className="form-error-banner" role="alert">{error}</p>}{saved && <p className="admin-save-success" role="status">Changes saved.</p>}<Button onClick={save} disabled={saving}>{saving ? "Saving..." : "Save changes"}</Button></div></SheetContent></Sheet>;
}
