import type { Metadata } from "next";
import { siteConfig } from "@/lib/site-config";
export const metadata: Metadata = { title: "Terms of Use", alternates: { canonical: "/terms" } };

const termsEmail = siteConfig.email;

export default function TermsPage() {
  return <main>
    <section className="legal-hero"><div className="site-container"><p className="eyebrow">Legal</p><h1>Terms of Use</h1><p>These terms govern use of the VISION. website and provide general information about engaging with VISION. Individual client work remains subject to its agreed proposal, quotation or project agreement.</p></div></section>
    <article className="legal-content site-container">
      <section><h2>1. About these terms</h2><p>By using this website, you agree to use it in accordance with these terms. These website terms do not replace a signed client proposal, quotation or service agreement.</p></section>
      <section><h2>2. Website use</h2><p>You may use this website for lawful purposes. You must not attempt to disrupt its operation, misuse its forms or content, gain unauthorised access, or use it in a way that could harm VISION., its service providers or other users.</p></section>
      <section><h2>3. Services and proposals</h2><p>Website and service descriptions are general information. The exact scope, deliverables, price, timeline, responsibilities and dependencies for client work are agreed separately in writing. Where applicable, the accepted proposal, quotation or project agreement takes precedence for that work.</p></section>
      <section><h2>4. Pricing and payments</h2><p>Public pricing shows the current setup price for the described packages. Unless agreed otherwise in writing, the standard website process requires a 50% deposit to begin and the remaining 50% before launch.</p><p>Website Care is optional after launch where selected. New pages, custom functionality, advanced integrations and other work outside the agreed package are quoted separately. VAT, where applicable, will be confirmed before work begins.</p></section>
      <section><h2>5. Website Care</h2><p>Website Care is optional after launch and is available for businesses that want managed hosting, backups, monitoring, technical support and ongoing minor content updates.</p><p>It has an initial 3-month minimum term. After that, it continues month-to-month and can be cancelled with 30 days’ notice. Included minor updates may cover text changes, image replacements, contact details, opening hours and small content adjustments. Unused maintenance time does not roll over.</p><p>New pages, custom functionality, integrations, redesign work, large content uploads and other work outside the agreed package are quoted separately. If a website is hosted or managed through VISION., available handover or migration options will be explained before the service ends.</p></section>
      <section><h2>6. Design revisions</h2><p>Professional Website Foundation includes 1 design revision round, Custom Growth Website includes 2 design revision rounds, and Advanced Digital Presence includes 3 design revision rounds during the agreed design phase.</p><p>A revision round means one consolidated set of feedback on the current design direction. Additional revision rounds or significant changes outside the agreed scope may be quoted separately.</p></section>
      <section><h2>7. Ownership and domains</h2><p>Once the project has been paid in full, the client owns the final website content and agreed project deliverables. The domain should be registered in the client’s name, and VISION. can assist with setup and management where required.</p><p>Third-party platforms, software, fonts, plugins and services remain subject to their own licences and terms.</p></section>
      <section><h2>8. Third-party services</h2><p>Websites may depend on hosting services, integrations, platforms or other third-party providers. Those services may have their own terms, pricing and availability. VISION. is not responsible for changes, interruptions or outages caused by third-party providers beyond its reasonable control.</p></section>
      <section><h2>9. Results and responsibilities</h2><p>Digital, SEO, advertising and marketing outcomes cannot be guaranteed. Search platforms, customer behaviour and third-party systems can change. Specific responsibilities, warranties and reasonable limitations for paid client work should be set out in the relevant project or service agreement.</p></section>
      <section><h2>10. Changes to these terms</h2><p>These terms may be updated as the website and service offering develop. The version available on this page applies to website use from the time it is published.</p></section>
      <section><h2>11. Contact</h2><p>Questions about these terms can be sent to <a href={`mailto:${termsEmail}`}>{termsEmail}</a>.</p></section>
    </article>
  </main>;
}
