import {
  BarChart3,
  Bot,
  Crosshair,
  Globe2,
  MapPin,
  Search,
  ShieldCheck,
} from "lucide-react";

export const services = [
  {
    slug: "web-design",
    seoTitle: "Website Design & Development Cyprus",
    seoDescription: "Custom websites for Cyprus businesses, designed around enquiries, bookings and sales: responsive design, fast development, SEO foundations and tracking.",
    title: "Website Design & Development",
    short: "Modern websites designed and developed around the business goals that matter: enquiries, bookings, calls and sales.",
    icon: Globe2,
    eyebrow: "Design & development",
    headline: "A website built to earn attention and turn it into business.",
    intro:
      "We combine strategy, UX, sharp visual design and reliable development into a fast, clear website that makes your business feel established from the first click.",
    benefits: [
      "Business and competitor discovery",
      "Customer journey and conversion strategy",
      "Tailored responsive design",
      "Fast, secure development and deployment",
      "WhatsApp, click-to-call and booking journeys",
      "Google Maps and contact integrations",
      "Copywriting guidance and content structure",
      "Analytics, Search Console and SEO foundations",
      "Launch support and an ongoing care plan",
      "Speed and performance optimisation",
    ],
    result: "A professional digital home that is easy to trust, easy to use and ready to grow.",
  },
  {
    slug: "local-seo",
    seoTitle: "Local SEO Services Cyprus",
    seoDescription: "Local SEO for businesses in Nicosia, Limassol, Larnaca and Paphos: keyword research, technical SEO, service and location content, and search tracking.",
    title: "Local SEO",
    short: "Search visibility shaped around your services, locations and the demand nearby customers show.",
    icon: Search,
    eyebrow: "Organic visibility",
    headline: "Be present when local customers are actively searching.",
    intro:
      "Local SEO connects your services with the searches people make in Nicosia, Limassol, Larnaca, Paphos, Paralimni, Ayia Napa and across Cyprus. We map local demand, service areas and the website signals search engines need to understand over time.",
    benefits: [
      "Local keyword and competitor research",
      "Service and location content planning",
      "Technical SEO and metadata",
      "Structured data and internal linking",
      "Search Console configuration",
      "Indexing and visibility checks",
      "Post-launch search health checks",
      "Search performance tracking",
    ],
    result: "Stronger search visibility without unrealistic promises or guaranteed rankings.",
  },
  {
    slug: "google-business",
    seoTitle: "Google Business Profile Optimisation Cyprus",
    seoDescription: "Set up and optimise your Google Business Profile: categories, services, hours, photos and a review strategy, so local customers can find and contact you.",
    title: "Google Business",
    short: "A complete and credible Google Business Profile that connects customers with the right information, website, services and actions.",
    icon: MapPin,
    eyebrow: "Local presence",
    headline: "Make the most important local search result work harder.",
    intro:
      "We audit and refine your Google Business Profile so customers can quickly understand what you do, where you operate and how to take the next step.",
    benefits: [
      "Primary and secondary category optimisation",
      "Accurate business information and opening hours",
      "Services, descriptions and website links",
      "Profile completeness review",
      "Photo and content recommendations",
      "Ethical review request strategy",
      "Local visibility and website alignment",
      "Posts and updates guidance",
    ],
    result: "A clearer, more complete profile that supports discovery and trust.",
  },
  {
    slug: "website-care",
    seoTitle: "Website Care, Hosting & Maintenance Cyprus",
    seoDescription: "Managed hosting, SSL, backups, monitoring and monthly content updates for your website, from €49 a month. Keep your site fast, secure and up to date.",
    title: "Website Care",
    short: "Hosting, monitoring, backups and routine updates that keep the website dependable after launch.",
    icon: ShieldCheck,
    eyebrow: "Ongoing care",
    headline: "Your website should stay fast, secure and up to date.",
    intro:
      "A website needs looking after once it is live. Our care plans keep technical health in good order and make routine monthly changes easy to manage.",
    benefits: [
      "Managed hosting, SSL and backups",
      "Security and uptime monitoring",
      "Technical and dependency updates",
      "Form and performance checks",
      "Analytics health checks",
      "Text, image, contact detail and opening-hour changes",
      "Support when a routine change needs attention",
      "Post-launch technical health checks",
    ],
    result:
      "A dependable website with routine changes handled and larger improvements scoped separately.",
  },
  {
    slug: "analytics",
    seoTitle: "Website Analytics & Conversion Tracking",
    seoDescription: "Track calls, WhatsApp clicks, bookings and form enquiries with GA4 and Search Console, so you know which pages and campaigns bring customers.",
    title: "Analytics & Tracking",
    short: "Measure calls, messages, bookings and forms so decisions are based on real customer signals.",
    icon: BarChart3,
    eyebrow: "Measurement",
    headline: "Visitors are useful. Actions are more useful.",
    intro:
      "We configure privacy-aware measurement around the actions that show commercial intent, giving you evidence for what generates interest.",
    benefits: [
      "Phone and WhatsApp click tracking",
      "Email and booking click tracking",
      "Contact and audit form submissions",
      "Pricing and service engagement",
      "Google Analytics 4 configuration",
      "Campaign and UTM attribution",
      "Conversion and engagement reporting",
      "Search Console performance insights",
    ],
    result: "A measurement setup that turns customer signals into better marketing decisions.",
  },
  {
    slug: "conversion-design",
    seoTitle: "Conversion-Focused Web Design Cyprus",
    seoDescription: "Page structure, calls to action, forms and trust signals designed to turn visitors into calls, bookings and enquiries, on mobile and desktop.",
    title: "Conversion-Focused Design",
    short: "Decision paths shaped around trust, reassurance and the action customers are ready to take.",
    icon: Crosshair,
    eyebrow: "Decision paths",
    headline: "Help customers move from interest to action.",
    intro:
      "We shape page structure, content hierarchy and calls to action around how people decide to call, message, book, enquire or buy.",
    benefits: [
      "Message and offer clarity",
      "Action-led call-to-action strategy",
      "Enquiry and booking paths",
      "WhatsApp and click-to-call actions",
      "Trust signals, reviews and reassurance",
      "Simplified forms and mobile usability",
      "Evidence-led journey improvements",
      "Conversion tracking setup",
    ],
    result: "A confident route from first impression to the action that matters to the business.",
  },
] as const;

export const customCapabilities = [
  {
    slug: "automation",
    seoTitle: "Lead & Booking Automation",
    seoDescription: "Connect your website to email, your CRM, bookings and newsletters so enquiries are routed and followed up automatically, without extra admin.",
    title: "Lead & Booking Automation",
    short: "Practical workflows added when a project genuinely benefits from them.",
    icon: Bot,
    eyebrow: "Custom capability",
    headline: "Useful workflows, where they make sense.",
    intro:
      "Automation is an optional layer for projects that need it, connecting simple business workflows without turning the website into an enterprise system.",
    benefits: [
      "Website form to email notification",
      "Enquiry to CRM webhook",
      "Booking confirmation flows",
      "Simple lead follow-up",
      "Newsletter signup to email platform",
      "Contact form to internal pipeline",
    ],
    result: "A practical workflow that removes a repetitive step while keeping the business in control.",
  },
] as const;

export const legacyServiceAliases = {
  maintenance: "website-care",
  "conversion-optimisation": "conversion-design",
} as const;

export const projects = [
  {
    slug: "aura-dental",
    image: "/images/aura-demo/treatment-hero.png",
    name: "AURA Dental",
    industry: "Dental Clinic",
    tone: "aura",
    statement: "Calm care. Clear choices.",
    concept: "A calm, premium and conversion-focused dental experience.",
    scope: "Strategy · UX/UI · Treatment pages · Booking flow",
    challenge: { title: "Nervous patients decide fast.", body: "Most people arrive at a dental website uneasy and short on time. When treatments, prices and the way to book are hard to find, they simply call the next clinic." },
    approach: { title: "Answer the worry, then offer the booking.", body: "Every treatment page follows the same order: what it is, how it feels, how long it takes, then one clear booking step. The questions patients hesitate to ask are answered before they have to." },
    direction: { title: "Warm neutrals instead of clinical white.", body: "Cream, sand and olive tones with a classic serif make the clinic feel reassuring and personal, while generous spacing keeps a lot of treatment detail easy to scan on a phone." },
    closing: "Is your clinic this easy to choose?",
    features: ["Appointment booking", "Treatment pages", "Doctors", "Reviews section", "Google Maps", "WhatsApp", "Click-to-call", "Gallery", "FAQ"],
  },
  {
    slug: "nova-estates",
    image: "/images/nova-demo/nova-hero.png",
    name: "NOVA Estates",
    industry: "Luxury Real Estate",
    tone: "nova",
    statement: "Cyprus properties, precisely presented.",
    concept: "A dark editorial property platform with immersive detail and effortless lead capture.",
    scope: "Strategy · UX/UI · Listings & search · Enquiry flow",
    challenge: { title: "Premium homes, ordinary browsing.", body: "High-value listings lose their pull when they sit in the same grid and filters as every property portal. Buyers at this level expect the browsing itself to feel considered." },
    approach: { title: "Let the property lead. Keep the enquiry close.", body: "Search and filters narrow the choice quickly, each home gets an editorial detail page, and a private enquiry is never more than one step away, including for developments shared before public launch." },
    direction: { title: "Navy, cream and a touch of gold.", body: "A dark editorial palette with classic serif headings gives the agency quiet authority and lets the photography carry every page." },
    closing: "Do your listings feel as good as the homes?",
    features: ["Property listings", "Search and filters", "Property detail", "Gallery", "Agent profile", "WhatsApp", "Enquiry", "Map"],
  },
  {
    slug: "vela-studio",
    image: "/images/work/vela-studio-cover.webp",
    name: "VELA Studio",
    industry: "Beauty / Wellness",
    tone: "vela",
    statement: "A quieter kind of confidence.",
    concept: "A warm, appointment-led beauty experience that makes choosing a treatment feel calm and personal.",
    scope: "Brand feel · UX/UI · Service menu · Booking",
    challenge: { title: "Choosing a treatment shouldn’t feel like homework.", body: "Beauty studios often list dozens of treatments with little guidance, so visitors leave unsure what to book or who will look after them." },
    approach: { title: "Guide the choice, then make booking effortless.", body: "Treatments sit in a short menu with plain descriptions and durations, therapists are introduced by name, and booking and WhatsApp stay within reach on every page." },
    direction: { title: "Soft ivory, warm browns, an unhurried pace.", body: "A custom serif, earthy tones and slow, gentle motion give the studio a premium feel that matches the atmosphere in the treatment room." },
    closing: "Does your studio feel like this online?",
    features: ["Service menu", "Appointment booking", "Team profiles", "Treatment gallery", "Reviews section", "WhatsApp", "Instagram integration", "Location and hours", "FAQ"],
  },
] as const;

/** Finished builds that are live in production. Cards link straight to the deployment. */
export const deployedProjects = [
  {
    slug: "zafiri-jewellery",
    image: "/images/work/zafiri-jewellery-cover.webp",
    name: "Zafiri Jewellery",
    industry: "Retail / E-commerce",
    url: "https://zafiri-jewellery.vercel.app/",
    summary: "A premium jewellery boutique store with engagement guidance, bespoke commissions, wishlist and secure checkout.",
  },
  {
    slug: "mastrohome",
    image: "/images/work/mastrohome-cover.webp",
    name: "MastroHome",
    industry: "Retail / Loyalty Platform",
    url: "https://mastrohome.vision.cy/",
    summary: "A clearance retail platform running four connected apps: public store, customer loyalty app, admin dashboard and cashier till.",
  },
] as const;

export const processSteps = [
  ["01", "Discover", "We understand your business, audience, competitors, goals and current challenges."],
  ["02", "Define", "We shape the structure, messaging and customer journey before design begins."],
  ["03", "Design", "We create the visual system and user experience around that strategy."],
  ["04", "Build", "We develop and test across devices, with the agreed integrations, SEO foundations and tracking."],
  ["05", "Launch & Grow", "We launch, track performance and keep improving SEO, analytics and what comes next."],
] as const;
